version: '3.1'

services:
    postgres:
      image: postgres
      container_name: esgi-pystone-postgres
      restart: always
      ports:
        - "8158:5432"

    web:
      build:
        context: .
        args:
        - http_proxy
        - https_proxy
        - no_proxy
      container_name: esgi-pystone-web
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/project
      ports:
        - "8058:8000"
      depends_on:
        - postgres
      environment:
        - http_proxy
        - https_proxy
        - no_proxy

    adminer:
      container_name: esgi-pystone-adminer
      image: adminer
      ports:
        - "8258:8080"