version: '3.1'

services:
    postgres:
      image: postgres
      container_name: esgi-pystone-postgres
      restart: always
#      ports:
#        - "8158:8000"
#      environment:
#          POSTGRES_PASSWORD: password

    web:
      build: .
      container_name: esgi-pystone-web
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/project
      ports:
        - "8058:8000"
      depends_on:
        - postgres

#    adminer:
#      container_name: esgi-pystone-adminer
#      image: adminer
#      restart: always
#      ports:
#        - "8258:8000"