# Generated by Django 2.1.1 on 2018-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=256)),
                ('dbf_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('card_set', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('player_class', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=256, null=True)),
                ('img_gold', models.CharField(max_length=256, null=True)),
                ('mechanics', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
