# Generated by Django 2.1.1 on 2018-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180921_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='health',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
