# Generated by Django 2.1.1 on 2018-09-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180924_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='credits',
        ),
    ]
