# Generated by Django 2.1.2 on 2018-10-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_deck_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
