# Generated by Django 2.1.2 on 2018-10-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181010_0852'),
        ('accounts', '0002_profile_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('cards', models.ManyToManyField(to='core.Card')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(to='core.Card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
