# Generated by Django 2.1.2 on 2018-11-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181026_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='numbercards',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='numbercards',
        ),
    ]
