# Generated by Django 2.1.2 on 2018-11-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181113_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='profilePlayer',
            new_name='profile',
        ),
    ]
