# Generated by Django 2.1.2 on 2018-11-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181113_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PlayerCard'),
        ),
    ]
