# Generated by Django 2.1.2 on 2018-11-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181113_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deckcard',
            old_name='card',
            new_name='player_card',
        ),
    ]
