# Generated by Django 2.1.2 on 2018-11-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181122_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
