DECK_CREATE = "deck.create"
DECK_UPDATE = "deck.update"
DECK_DELETE = "deck.delete"
CARDS_BUY = "cards.buy"
CARDS_SELL = "cards.sell"
PROFILE_SUBSCRIBE = "profile.subscribe"
PROFILE_UNSUBSCRIBE = "profile.unsubscribe"
